#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import cv2
import myimutils as myim
import sys
import argparse
import numpy as np
import random


ap = argparse.ArgumentParser()
ap.add_argument("infile",help="Name of the input animation",type=str)
ap.add_argument("-o","--outfile",required=False,help="Name of the output file",default='default.gif')
ap.add_argument("-f","--frequency",required=False,help="Frequency of the stutter",type=float,default=0.25)
args=vars(ap.parse_args())

imlist1,durations = myim.read_gif(args['infile'])
shape=imlist1[0].shape
blank_frame=np.zeros((shape[0],shape[1],3),dtype='uint8')

i=0
nframes=int(1/args['frequency'])
for i in range(len(imlist1)):
    if random.randrange(0,nframes)==0:
        imlist1[i]=blank_frame

myim.gif_viewer(imlist1,durations,'Result')
imlist1=myim.convert_to_PIL(imlist1)
myim.write_animation(imlist1,durations,args['outfile'])
