#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import numpy as np
import cv2
import myimutils as myim
import sys
import argparse
import mycolortools as mycolor
import tiletools as tt


ap = argparse.ArgumentParser()
ap.add_argument("game",help="Game that first tileset is from",type=str)
ap.add_argument("map",help="Name of the first tileset",type=str)
ap.add_argument("game2",help="Game that the second tileset is from",type=str)
ap.add_argument("map2",help="Name of the second tileset",type=str)
ap.add_argument("game_out",help="Game that the output tileset is assigned to",type=str)
ap.add_argument("map_out",help="Name of the output tileset",type=str)
ap.add_argument("-s","--size",required=False,help="Tile Size",type=int,default=8)
args=vars(ap.parse_args())

size=args['size']
tileset1=tt.tileset(args['map'],game=args['game'],tilesize=(size,size))
tileset2=tt.tileset(args['map2'],game=args['game2'],tilesize=(size,size))
tileset1.append(tileset2.tiles)
tileset1.save_tiles(args['game_out'],filename=args['map_out'])

