#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import cv2
import myimutils as myim
import sys
import argparse


ap = argparse.ArgumentParser()
ap.add_argument("infile",help="Name of the input animation",type=str)
ap.add_argument("resolution",help="The source resolution (e.g., 256x208)",type=str)
ap.add_argument("-o","--outfile",required=False,help="Name of the output file",default='default.gif')
args=vars(ap.parse_args())

imlist1,durations = myim.read_gif(args['infile'])
fx,fy=myim.axis_ratio_34(args['resolution'])
print('fx = ',fx,' fy = ',fy)

i=0
for i in range(len(imlist1)):
    imlist1[i]=cv2.resize(imlist1[i],(0,0),fx=fx,fy=fy)

myim.gif_viewer(imlist1,durations,'Result')
imlist1=myim.convert_to_PIL(imlist1)
myim.write_animation(imlist1,durations,args['outfile'],pil=0)
