#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python37/python

import myimutils
import sys
import os
from PIL import Image
import cv2

ims,durations=myimutils.read_gif(sys.argv[1])
dum=myimutils.gif_viewer(ims,durations,sys.argv[1])
