#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import argparse
import numpy as np
import cv2
import sys
import myimutils as myim
import mycolortools as mycolor

ap = argparse.ArgumentParser()
ap.add_argument("infile",help="Name of the input background file",type=str)
ap.add_argument("-o","--outfile",required=False,help="Name of the output file",default='test.png')
ap.add_argument("-c","--color",required=False,help="Color to use in edit",default='255 255 255')
args=vars(ap.parse_args())

sys.setrecursionlimit(1000000)
image=cv2.imread(args['infile'],cv2.IMREAD_UNCHANGED)

if args['color']!='white':
    color=mycolor.parse_color(args['color'])
else:
    color=args['color']
newim=myim.pix_edit(image,title=args['infile'],color=color)
if type(newim) is not int:
    cv2.imwrite(args['outfile'],newim)
