#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import cv2
import myimutils as myim
import sys
import argparse


ap = argparse.ArgumentParser()
ap.add_argument("infile",help="Name of the input animation",type=str)
ap.add_argument("resize_factor",help="Factor by which to resize the image",type=float)
ap.add_argument("-o","--outfile",required=False,help="Name of the output background file",default='test.gif')
args=vars(ap.parse_args())

imlist1,durations = myim.read_gif(args['infile'])

i=0
shape=(int(imlist1[0].shape[0]*args['resize_factor']),int(imlist1[0].shape[1]*args['resize_factor']))
print(shape,imlist1[0].shape)
for i in range(len(imlist1)):
    imlist1[i]=cv2.resize(imlist1[i],(shape[1],shape[0]),interpolation=cv2.INTER_NEAREST)

myim.gif_viewer(imlist1,durations,'Result')
imlist1=myim.convert_to_PIL(imlist1)
myim.write_animation(imlist1,durations,args['outfile'])
