#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import random
import cv2
import myimutils as myim
import myspritetools as myspr
import mycolortools as mycolor
import sys
import numpy as np
import argparse


ap = argparse.ArgumentParser()
ap.add_argument("game",help="Name of the game the sprite is from",type=str)
ap.add_argument("object",help="Name of the object the sprite represents",type=str)
ap.add_argument("-x","--sizex",required=False,help="Number of sprites in the x direction",type=int,default=30)
ap.add_argument("-y","--sizey",required=False,help="Number of sprites in the y direction",type=int,default=15)
ap.add_argument("-z","--zoom",required=False,help="Zoom factor for sprite images",type=int,default=3)
ap.add_argument("-f","--flips",required=False,help="Show flipped versions of sprites as well?",type=int,default=0)
ap.add_argument("-p","--pad",required=False,help="Pixels between sprites",type=int,default=0)
ap.add_argument("-c","--color",required=False,help="Background color",type=str,default='48 40 36')
ap.add_argument("-o","--outfile",required=False,help="Name of the output image file",default='default.png')
ap.add_argument("-i","--infile",required=False,help="Name of the input list of sprites to show",default='None')
args=vars(ap.parse_args())

game=args['game']
object=args['object']
mysprite=myspr.Sprite(game,object,'all')
mysprite.resize(args['zoom'])
if args['flips']==1:
    mysprite.save_flips()
(dum,diffx,diffy)=mysprite.maxsize()
nsprites=len(mysprite.data)
imsize_x=args['sizex']*(diffx+args['pad'])
imsize_y=args['sizey']*(diffy+args['pad'])
new_img=np.zeros((imsize_y,imsize_x,3),dtype='uint8')
new_img=myim.add_texture(new_img)
#bgcolor=mycolor.parse_color(args['color'])
#new_img[:,:,0:3]=bgcolor[0:3]
#new_img=myim.add_border(new_img,width=args['pad'])
nx=args['sizex']

if args['infile']!='None':
    spritenums=np.loadtxt(args['infile'],dtype='int')
else:
    spritenums=range(nsprites)
i=0
for j in spritenums:
    pos_x=(i%nx)*(diffx+args['pad'])+int(diffx/2)+args['pad']
    pos_y=int(i/nx)*(diffy+args['pad'])+int(diffy/2)+args['pad']
    pos_try=(pos_x,pos_y)
    print(pos_try, imsize_x,imsize_y)
    new_img=mysprite.overlay_frame(new_img,pos_try,j)
    i+=1

myim.img_viewer(new_img)
cv2.imwrite(args['outfile'],new_img)
