#!/c/Users/sp4ce/AppData/Local/Programs/Python/Python38-32/python

import random
import cv2
import myimutils as myim
import myspritetools as myspr
import sys
import numpy as np
import argparse


ap = argparse.ArgumentParser()
ap.add_argument("game",help="Name of the game the sprite is from",type=str)
ap.add_argument("object",help="Name of the object the sprite represents",type=str)
ap.add_argument("-x","--sizex",required=False,help="Number of pixels in the x direction",type=int,default=300)
ap.add_argument("-y","--sizey",required=False,help="Number of pixels in the y direction",type=int,default=150)
ap.add_argument("-z","--zoom",required=False,help="Zoom factor for sprite images",type=int,default=3)
ap.add_argument("-c","--color",required=False,help="Background color",type=str,default='black')
ap.add_argument("-o","--outfile",required=False,help="Name of the output image file",default='default.png')
args=vars(ap.parse_args())

game=args['game']
object=args['object']
mysprite=myspr.Sprite(game,object,'all')
mysprite.resize(args['zoom'])
imsize_x=args['sizex']*args['zoom']
imsize_y=args['sizey']*args['zoom']
new_img=np.zeros((imsize_y,imsize_x,3),dtype='uint8')
nsprites=len(mysprite.data)
(dum,diffx,diffy)=mysprite.maxsize()
nx=int(imsize_x/diffx)
for i in range(nsprites):
    pos_x=(i%nx)*diffx
    pos_y=int(i/nx)*diffy
    pos_try=(pos_x,pos_y)
    new_img=mysprite.overlay_frame(new_img,pos_try,i)

myim.img_viewer(new_img)
